name = "ZsigmondyChebyshev"
defaultTargets = ["ZsigmondyChebyshev"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"

[[lean_lib]]
name = "ZsigmondyChebyshev"
